# Generated by Django 4.1 on 2022-08-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_remove_post_downvotes_remove_post_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='post/covers/default.png', upload_to='post/covers'),
        ),
    ]
